{{- if .Values.assets.enabled }}
{{- $component := "assets" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rdoc.componentName" (dict "root" . "component" $component) }}
  labels:
    {{- include "rdoc.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
spec:
  replicas: {{ .Values.assets.replicaCount }}
  selector:
    matchLabels:
      {{- include "rdoc.componentSelectorLabels" (dict "root" . "component" $component) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rdoc.componentSelectorLabels" (dict "root" . "component" $component) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.assets.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: {{ include "rdoc.image" (dict "root" . "repository" .Values.assets.image.repository "tag" .Values.assets.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 30
          resources:
            {{- toYaml .Values.assets.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.assets.containerSecurityContext | nindent 12 }}
      {{- with .Values.assets.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.assets.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.assets.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
