{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rdoc.secretName" . }}
  labels:
    {{- include "rdoc.labels" . | nindent 4 }}
type: Opaque
stringData:
  TWITCH_CLIENT_ID: {{ .Values.secrets.data.twitchClientId | quote }}
  TWITCH_CLIENT_SECRET: {{ .Values.secrets.data.twitchClientSecret | quote }}
  DISCORD_BOT_TOKEN: {{ .Values.secrets.data.discordBotToken | quote }}
  DISCORD_GUILD_ID: {{ .Values.secrets.data.discordGuildId | quote }}
{{- end }}
